project:
  type: website
  output-dir: docs

website:
  title: "Zheng(Zeb) Yang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Zeb_resume.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

